sudo: false

language: scala

scala:
  - "2.11.11"
  - "2.12.4"

jdk: oraclejdk8

matrix:
  include:
    - env: SBT_VERSION=0.13.16
      scala: "2.12.4"
    - env: SBT_VERSION=1.1.2
      scala: "2.12.4"

env:
  - TRAVIS_NODE_VERSION="7.10.1"
  - TRAVIS_NODE_VERSION="8.9.1"
  - TRAVIS_NODE_VERSION="9.10.1"

install:
  - travis/setupLLVM.sh
  - travis/setNodeVersion.sh

script:
  - travis/cleanCache.sh
  - sbt ++$TRAVIS_SCALA_VERSION test
  - travis/testSbtPlugin.sh

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
